library(identifier: 'jenkins-shared@master',
        changelog: false,
        retriever: modernSCM([$class       : 'GitSCMSource',
                              remote       : 'https://github.com/diwakar-kuruba/jenkins-shared.git',
                              credentialsId: 'dk-github'])
)

pipelineSpringBoot {
    artifactName = "Dms_auth_service"
}
